#!/usr/bin/env bash
# This script changes the IP Adresses
cp /etc/hosts /etc/hosts.backup #Save
echo -n > /etc/hosts #Clear
echo "127.0.0.2 localhost" >> /etc/hosts #localhost
echo "8.8.8.8 facebook.com" >> /etc/hosts #FB
